import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState(null);

  // send from parent to index.html (iframe)
  const handleClickSendDataIframe = () => {
    const iframeWin = document.getElementById("iframe-id").contentWindow;
    iframeWin.postMessage("MESSAGE FROM PARENT", "*");
  };

  // retrieve data from index.html (iframe) to parent
  useEffect(() => {
    window.addEventListener(
      "message",
      function message(e) {
        if (e.data.from === "iframe-child") {
          setData(e.data.data);
        }
      },
      false
    );

    return () => {
      window.removeEventListener("message", function message() {}, false);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button type="button" onClick={handleClickSendDataIframe}>
          Click To Send Data To Iframe
        </button>
        <p>{data}</p>
        <iframe
          src="/index.html"
          title="Example iframe"
          width="100%"
          height="500px"
          id="iframe-id"
        />
      </main>
    </>
  );
}
